x-common-env: &common-env
  SECRET: "esta_es_mi_compleja_clave_secreta_para_jwt_2026_academia_noafer"
  JWT_SECRET: "esta_es_mi_compleja_clave_secreta_para_jwt_2026_academia_noafer"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/academia_noafer
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
services:

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academia_noafer
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      <<: *common-env
    depends_on:
      - auth-service
      - calificaciones-service
      - certificado-service
      - clases-service
      - evaluaciones-service
      - inscripciones-service
      - pago-service
      - user-service
      - notificaciones-service
      - mensajeria-service



  pago-service:
    build: ./pago-service
    ports:
      - "8082:8082"
    environment:
      <<: *common-env
    depends_on:
      mysql:
        condition: service_healthy
  clases-service:
    build: ./clases-service
    ports:
      - "8083:8083"
    environment:
      <<: *common-env
    depends_on:
      mysql:
        condition: service_healthy

  evaluaciones-service:
    build: ./evaluaciones-service
    ports:
      - "8084:8084"
    environment:
      <<: *common-env
    depends_on:
      mysql:
        condition: service_healthy

  inscripciones-service:
    build: ./inscripciones-service
    ports:
      - "8085:8085"
    environment:
      <<: *common-env      
    depends_on:
      mysql:
        condition: service_healthy
      
  user-service:
    build: ./user-service
    ports:
      - "8086:8086"
    environment:
      <<: *common-env
    depends_on:
      mysql:
        condition: service_healthy

  auth-service:
    build: ./auth_service
    ports:
      - "8087:8087"
    environment:
      <<: *common-env
    depends_on:
      mysql:
        condition: service_healthy


  certificado-service:
    build: ./certificado_service
    ports:
      - "8088:8088"
    environment:
      <<: *common-env      
    depends_on:
      mysql:
        condition: service_healthy      

  calificaciones-service:
    build: ./calificaciones_service
    ports:
      - "8089:8089"
    environment:
      <<: *common-env      
    depends_on:
      mysql:
        condition: service_healthy      

  notificaciones-service:
    build: ./notificaciones-service
    ports:
      - "8090:8090"
    environment:
      <<: *common-env      
    depends_on:
      mysql:
        condition: service_healthy 

  mensajeria-service:
    build: ./mensajeria-service 
    ports:
      - "8091:8091"
    environment:
      <<: *common-env      
    depends_on:
      mysql:
        condition: service_healthy     
