spring.application.name=pago-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/db_academia_pagos?createDatabaseIfNotExist=true
api.curso.exists=http://localhost:8080/api/cursos/%d/existe
SECRET=esta_es_mi_compleja_clave_secreta
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.enabled=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

