server:
  port: 8080
# 8080 api 
# 8082 pagos
# 8083 clases 
# 8084 evaluaciones
# 8085 inscripciones
# 8086 usuarios
# 8087 auth
# 8088 certificados
# 8089 calificaciones
spring:
  main:
    web-application-type: reactive


  cloud:
    gateway:
      server:
        webflux:
          routes:

            # - id: swagger-ui
            #   uri: https://localhost:8080
            #   predicates:
            #     - Path=/swagger-ui/** 


            - id: auth-service
              uri: http://auth-service:8087
              predicates:
                - Path=/api/auth/**,/v3/api-docs/auth
              filters:
                - RewritePath=/v3/api-docs/auth, /v3/api-docs

            - id: calificaciones-service
              uri: http://calificaciones-service:8089
              predicates:
                - Path=/api/calificaciones/**, /api/promedios/**, /v3/api-docs/calificaciones
              filters:
                - RewritePath=/v3/api-docs/calificaciones, /v3/api-docs

            - id: certificado-service
              uri: http://certificado-service:8088
              predicates:
                - Path=/api/certificados/**,/v3/api-docs/certificados
              filters:
                - RewritePath=/v3/api-docs/certificados, /v3/api-docs

            - id: user-service
              uri: http://user-service:8086
              predicates:
                - Path=/api/usuarios/**, /api/roles/**, /v3/api-docs/usuarios, /v3/api-docs/roles
              filters:
                - RewritePath=/v3/api-docs/usuarios, /v3/api-docs

            - id: pago-service
              uri: http://pago-service:8082
              predicates:
                - Path=/api/pagos/**, /api/transacciones/**, /v3/api-docs/pago, /v3/api-docs/pagos
              filters:
                - RewritePath=/v3/api-docs/pagos, /v3/api-docs

            - id: clases-service
              uri: http://clases-service:8083
              predicates:
                - Path=/api/cursos/**, /api/categorias/**, /api/clases/**, /v3/api-docs/cursos, /v3/api-docs/clases, /v3/api-docs/categorias
              filters:
                - RewritePath=/v3/api-docs/clases, /v3/api-docs

            - id: evaluaciones-service
              uri: http://evaluaciones-service:8084
              predicates:
                - Path=/api/evaluaciones/**, /api/preguntas/**, /api/alternativas/**, /v3/api-docs/evaluaciones
              filters:
                - RewritePath=/v3/api-docs/evaluaciones, /v3/api-docs

            - id: inscripciones-service
              uri: http://inscripciones-service:8085
              predicates:
                - Path=/api/inscripciones/**, /api/cupos/**, /v3/api-docs/inscripciones, /v3/api-docs/cupos
              filters:
                - RewritePath=/v3/api-docs/inscripciones, /v3/api-docs

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 1. Autenticación (Auth)
        url: /v3/api-docs/auth
      - name: 2. Calificaciones
        url: /v3/api-docs/calificaciones
      - name: 3. Certificados
        url: /v3/api-docs/certificados
      - name: 4. Pagos
        url: /v3/api-docs/pagos
      - name: 5. Clases
        url: /v3/api-docs/clases
      - name: 6. Evaluaciones
        url: /v3/api-docs/evaluaciones
      - name: 7. Inscripciones
        url: /v3/api-docs/inscripciones
      - name: 8. Usuarios
        url: /v3/api-docs/usuarios



jwt:
  secret: esta_es_mi_compleja_clave_secreta_para_jwt_2026_academia_noafer