spring.application.name=auth_service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/db_academia_usuarios
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=false  

jwt.secret=esta_es_mi_compleja_clave_secreta
jwt.expiration=3600000

jwt.secret=academiaNoaferClaveSecretaSuperSeguraParaJWT2026123456789

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=truue
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true